version: '3'

services:

  api:
    build: .
    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: '1213'
      DB_NAME: mydb

  postgres:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1213
      POSTGRES_DB: mydb

    ports:
      - "5432:5432"